### ISSUE TITLE
Engine Driver on ESU MC2 loco headlight turns off unexpectedly

### ISSUE THREAD

**Issue by KenNinomiya** [JMRI/EngineDriver#212]
Hardware: ESU MC2
OS: Android 4.1.1
Engine Driver version: 2.18
JMRI version: JMRI for Raspberry Pi by Steve Todd
DCC: CVP EasyDCC
If it makes a difference: Engine Driver theme used is "High Contrast Outline"

Minor issue noticed during ops session. Intermittent headlight loss (turns off). Light "button" indicates light function still "on", but headlight is off on loco. To turn light back on, I have to cycle through the on off on using the "Light" "button."

I'm not sure what triggered this each time. Once, it was after the loco was moving but I had "swiped up to lock the screen." Another time, I noticed the light was off after the loco had slight stall or hiccup. However, there was another time when I had no issue with the loco's running when I noticed that the light was off.

I suspect this is an Engine Driver issue and not hardware related since the Engine Driver is running under Android on the MC2, but I thought I'd mention it's running on the MC2 anyway.

Ken

**Comment by mstevetodd** [comment]
@KenNinomiya does the light indicator actually change from on to off, or does the indicator not update after you send a change? Not much change of debugging it without a consistent way to repeat. Even then, it'll be difficult since I don't have CVP hardware.
As background, the indicator changes on a message from the WiThrottle server. If that message isn't sent, the indicator won't update.

**Comment by KenNinomiya** [comment]
The indicator on the MC2 display remains in the "on" setting (bright border and text) when the loco headlight goes out. The indicator on the display will dim and highlight again when I press/touch to cycle and restore the headlight back on on the loco.

Sent from my iPhone

> On Apr 8, 2018, at 1:37 PM, mstevetodd <notifications@github.com> wrote:
> 
> @KenNinomiya does the light indicator actually change from on to off, or does the indicator not update after you send a change? Not much change of debugging it without a consistent way to repeat. Even then, it'll be difficult since I don't have CVP hardware.
> As background, the indicator changes on a message from the WiThrottle server. If that message isn't sent, the indicator won't update.
> 
____________________________________________________________
After Weeks Of Rumors, Joanna Gaines Comes Clean
risingstarnewspaper.com
http://thirdpartyoffers.juno.com/TGL3131/5aca8cd1b6a8ecd10863st02vuc

**Comment by KenNinomiya** [comment]
Sorry, never thought about trying the default theme.

Ken

Sent from my iPhone

> On Apr 8, 2018, at 4:18 PM, mstevetodd <notifications@github.com> wrote:
> 
> @KenNinomiya do you see the same behavior with the default theme?
> 
> ―
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
____________________________________________________________
1 Simple Trick Removes Eye Bags & Lip Lines in Seconds
Fit Mom Daily
http://thirdpartyoffers.juno.com/TGL3131/5acaa6723bc6e26710e24st02duc

**Comment by mstevetodd** [comment]
It would also be helpful to try it with another command station type, even a simulator. Feel free to use my jmri.mstevetodd.com:44444 if you'd like.
I'm trying to narrow down if we have a CVP problem or and EngineDriver problem.

**Comment by KenNinomiya** [comment]
Since your simulator won't have an actual loco to monitor the headlight, that won't work. I'll have to get on an actual layout to test.

Sent from my iPhone

> On Apr 8, 2018, at 4:58 PM, mstevetodd <notifications@github.com> wrote:
> 
> It would also be helpful to try it with another command station type, even a simulator. Feel free to use my jmri.mstevetodd.com:44444 if you'd like.
> I'm trying to narrow down if we have a CVP problem or and EngineDriver problem.
> 
> ―
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
____________________________________________________________
1 Cup of This Before Bedtime ''Ends'' Tinnitus (Ear Ringing)
Healthier Patriot
http://thirdpartyoffers.juno.com/TGL3131/5acabba3254d23ba2778fst02vuc

**Comment by KenNinomiya** [comment]
The only thing is, I've used this MC2 on this CVP layout since ED 2.15 or so, and I don't recall having to do this during ops before.

I'll check with my own JMRI on CabControl system to see whether the issue follows this MC2 or not.

I might be able to talk the manager of the CVP to let me run a test this week.

Ken

Ken Ninomiya
Oxnard, CA

____________________________________________________________
Royal Family Tragedy Unfolds
risingstarnewspaper.com
http://thirdpartyoffers.juno.com/TGL3131/5acad2df1cb3052dd4569st02vuc

**Comment by KenNinomiya** [comment]
@mstevetodd Robin is correct.

I tried the ED on my ESU CabControl command station, and I get no loss of headlight, even after tipping one side of the loco off the track. The headlight comes back on when placing wheels back down.

I ran a test on the EasyDCC layout again today. I noticed headlight flicker just before the headlight completely went out. When I tip the loco over, the headlight will not go back on when the loco is placed back down. The headlight indicates "on" on the touchpad and must be cycled off then back on to have the headlight return to lit on the loco.

So, the issue seems to be that the EasyDCC command station doesn't send headlight state commands after the initial command, or very infrequent.

Since this can't be fixed through ED, I'm closing this issue.

Ken

Ken Ninomiya
Oxnard, CA

**Comment by n3ix** [comment]
Ken - thanks for the thorough testing.

Steve and Peter - as mentioned I run into fairly frequently during Ops, for sure on NCE systems, perhaps others.  I wonder if there is something we can do.  The headlight is typically transmitted in a DCC Function Group One packet.  This packet contains F1-F4 in addition to the headlight.  If we (optionally) periodically briefly toggled one of those functions, it would most likely trigger the Command Station to send Function Group One packets to that decoder.  If the toggle was done quickly enough to be unnoticeable but not so quickly that a command station might ignore it, the headlight would get refreshed in the decoder.  Typically functions are assigned as F0 (Light), F1 (Bell), F2 (Horn) and F3 (sometimes Short Horn), these might be noticeable, so how about it we try briefly toggling F4 once per heartbeat or something like that?

**Comment by flash62au** [comment]
Robin,
I am not sure a I can provide any serious input into this discussion, but a
question/observation.

I would be interested to sample a number of different sound decoders to see
what F4 does in them.

If it plays a sound in some/any decoders it could be annoying to
periodically toggle it.
Toggling the headlight, while a bit odd, 'may' prove less annoying.

Peter

**Comment by n3ix** [comment]
@flash62au F0 might be ok too.  What we need to do is "trick" the command station into thinking it needs to send Function Group One.  It might be that toggling F0 back and forth with no delay would do that, it might be that some command station code is smart enough to reject (also need to confirm that WiT doesn't discard rapid changes).  With functions other than F0 I think the command station might have to send every change since some decoder effects are triggered by the function off-on or on-off transition rather than the level.  That's why I initially thought about F4.  But F0 does sound safer it is works, just don't want to see the headlight flash so maybe try sending the two toggle commands in immediate succession and see what happens.

**Comment by mstevetodd** [comment]
I'm not a fan of doing this in EngineDriver at all. 
IF it needs doing, it seems like it should be handled in JMRI itself, either in the WiThrottle Server, or in the throttle implementations.

**Comment by n3ix** [comment]
@mstevetodd I agree with you.  Figured the chances of getting in JMRI itself right off the bat weren't good but it would be pretty easy to implement and test as a user pref in ED.

@KenNinomiya  I operate regularly on a couple NCE layouts.  Despite enabling the refresh option in the command station they still exhibit this problem so perhaps the command station refresh does not really work?  Yes some command stations refresh f0-f4 more (effectively) than others, that's why I'd make this feature an option select through a user preference.  It's pretty unusual to have F0 remapped, so to just test the idea out it would probably be good enough.

All: This wasn't meant as a cure-all, just thought it might have its place on select systems.  There are other weird things that come along with this.  For instance the short horn function (if used) can also create issues when a loco loses power momentarily.  For soundtrax decoders it seems they trigger the short horn on either a off-on or an on-off transition of the assigned Function.  In order to avoid getting 2 toots, you have to make the function latching in ED/JMRI.  After the decoder loses power and then resets, it sets whatever function is assigned to the Short Horn internally to Off.  Now suppose the short horn is assigned to F3 and that F3 happens to be On when the decoder momentarily lost power.  The next time the decoder gets a Function Group1 message, such as when you notice that the headlight is off and quickly toggle it in ED to get it back on,  the F3 value will also get sent and presto - a short horn toot :)
