### ISSUE TITLE
EngineDriver not compatible

### ISSUE THREAD

**Issue by SonnysHansen** [JMRI/EngineDriver#213]
When trying to download EngineDriver version 2.18 to my ESU mobile control II from Google Play Store, I get this message " Your device isn't compatible with this version".
Do I do something wrong?
regards,
Sonny Hansen
Denmark

**Comment by mattharris** [comment]
I'll have to look at this at the weekend as do not have access to hardware at the moment.
However, a quick thought comes to mind - didn't we add support for accelerometer based feedback during this past development phase? Only I do not think that the MCII has such hardware installed. It could be the way we're specifying the hardware requirements tripping us up.

Looking at the relevant line in the manifest, https://github.com/JMRI/EngineDriver/blob/master/AndroidManifest.xml#L26 we do not explicitly say if it's mandated or not. 

Looking at the Android docs, https://developer.android.com/guide/topics/manifest/uses-feature-element.html#required it implies that as we've not included a suitable `android:required` declaration, it defaults to `true` thereby meaning that any hardware without an accelerometer will be marked incompatible. That this didn't come up during testing is due to Google Play using the `uses-feature` declaration for compatibility but direct loading not doing so.

**Comment by flash62au** [comment]
oh..

Peter

**Comment by flash62au** [comment]
I have added a new Pull Request to with the declaration included.

I have no way to test it though.

Peter

**Comment by n3ix** [comment]
I added the change to the uses-feature line in my copy of AndroidManifest.  It loaded fine on the device, but as Matt pointed out this change only impacts loading from Play.  I will uninstall the test version and retest it from Play it once Steve uploads a new version.

**Comment by n3ix** [comment]
The 2.18.1 beta loaded successfully from the Playstore.

**Comment by mstevetodd** [comment]
@SonnysHansen if you'd like to verify the 2.18.1 beta version on your MCII, please visit this site 
https://play.google.com/apps/testing/jmri.enginedriver
and sign up to receive Beta updates:
